org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=false

mod_version=1.5.2
mod_group_id=com.prefab.addon
archives_base_name=prefab-custom-addon

neo_version=21.1.233
parchment_minecraft_version=1.21.1
parchment_mappings_version=2024.11.17

# 通过 junction 引用 Java 21 (避开中文路径编码问题)
org.gradle.java.home=C:/java21
