modLoader="javafml"
loaderVersion="[4,)"
license="MIT"
showAsResourcePack=false

[[mods]]
modId="prefab_custom_addon"
version="${mod_version}"
displayName="Prefab Custom Addon"
authors="veyne"
description='''
Prefab Custom Addon - An extension system for the Prefab mod.
Adds in-game browser (Z) and creator (X) for community-made building packs.
'''

# 依赖 Prefab 主模组
[[dependencies.prefab_custom_addon]]
modId="prefab"
mandatory=true
versionRange="[1.0.7,)"
ordering="NONE"
side="BOTH"

# 依赖 LDLib2 模组
[[dependencies.prefab_custom_addon]]
modId="ldlib2"
mandatory=true
versionRange="[2.2,)"
ordering="NONE"
side="CLIENT"

# Mixin 配置
[[mixins]]
config="prefab-custom-addon.mixins.json"
